sudo: false

language: node_js

node_js:
 - 4.2

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

services:
  - mongodb

before_script:
  - sleep 15

install:
  - npm install
  - npm install -g jscs

script:
  - jscs .
  - npm test
